apiVersion: v1
kind: PersistentVolume
metadata:
   name: awspv
   labels:
     type: awspv
spec:
   capacity:
     storage: 20Gi
   accessModes:
     - ReadWriteOnce
   persistentVolumeReclaimPolicy: Retain
   nfs:
     server: fs-070000ec0f339d8b1.efs.ap-south-1.amazonaws.com
     path: /test

