apiVersion: v1
kind: ReplicationController
metadata:
     name: myngpodlive
spec:
  replicas: 5
  template:
    metadata:
       labels:
         app: live
    spec:
     containers:
           - image: nginx
             name: ngcontainer
             ports:
               - containerPort: 80
             livenessProbe:
                   httpGet:
                      path: /index.html
                      port: 80
                   initialDelaySeconds: 10
